Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -69,6 +69,7 @@ jobs:
 
       - name: Check APK File Exists
         run: |
+          ls -lah bin/
           if [ -f bin/*.apk ]; then
             echo "✅ APK file generated successfully!"
           else
@@ -88,3 +89,8 @@ jobs:
         with:
           name: buildozer-log
           path: buildozer_log.txt
+          
+      - name: Check `bin/` Folder (APK File Exist?)
+        run: |
+          echo "Checking bin/ folder..."
+          ls -lah bin/ || echo "❌ bin/ folder NOT found!"
